/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Thogakade.views;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Thogakade.controller.ControllerFactory;
import lk.ijse.Thogakade.controller.custom.CustomerController;
import lk.ijse.Thogakade.dto.CustomerDTO;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Viraj jayasanka
 */
public class allCustomerManagee extends javax.swing.JPanel {
               private CustomerController ctrlCustomer;
               private DefaultTableModel dtmCustomer;
              
    /**
     * Creates new form allCustomerManagee
     */
    public allCustomerManagee() {
        initComponents();
        ctrlCustomer = (CustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER);
        dtmCustomer = (DefaultTableModel) AllAddCustomerTabel.getModel();
        loadData();
    }

    //load tabel
    private void loadData() {

        dtmCustomer.setRowCount(0);

        try {
            ArrayList<CustomerDTO> allCustomers = ctrlCustomer.getAll();

            if (allCustomers == null) {
                return;
            }

            for (CustomerDTO customer : allCustomers) {
                Object[] rowData = {
                    customer.getId(),
                    customer.getName(),
                    customer.getAddress(),
                    customer.getTelePoneNO(),
                    customer.getDate(),
                };
                dtmCustomer.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(allCustomerManagee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
//
    //revome textField
     private void clearFields() {
        txtCustomerId.setText("");
        txtCustomerName.setText("");
        txtCustomerAddress.setText("");
        txtCustomerTelePoneNo.setText("");
        txtDate.setText("");
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCustomerTelePoneNo = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtCustomerId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllAddCustomerTabel = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("CUSTOMER ID");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("DATE");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("CUSTOMER TELEPONE NO");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("CUSTOMER ADDRESS");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("CUSTOMER NAME");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtCustomerTelePoneNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerTelePoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerTelePoneNoActionPerformed(evt);
            }
        });
        add(txtCustomerTelePoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 260, 30));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 253, 260, 30));

        txtCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 260, 30));

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 280, 30));

        jLabel1.setFont(new java.awt.Font("Sinhala-Lasitha-1", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/customerDetails.png"))); // NOI18N
        jLabel1.setText("CUSTOMER MANAGE FORM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 610, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/update Customer.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 150, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/search customer 1.png"))); // NOI18N
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/delete customer ican1.png"))); // NOI18N
        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SEARCH CUSTOMER");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 280, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 82, 1090, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1090, 10));

        txtCustomerId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 260, 30));

        AllAddCustomerTabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AllAddCustomerTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customerID", "customerName", "customerAdderss", "cutomerTelepone_NO", "AddDate"
            }
        ));
        AllAddCustomerTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllAddCustomerTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AllAddCustomerTabel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 1050, 260));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/Save button ican.png"))); // NOI18N
        jButton2.setText("Save Add Customer Detail Doument");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 310, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Show Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        dtmCustomer.setRowCount(0);
        String Date = txtDate.getText();
        String CustomerTelePoneNo = txtCustomerTelePoneNo.getText();
        String CustomerName = txtCustomerName.getText();
        String CustomerAddress = txtCustomerAddress.getText();
        String CustomerId = txtCustomerId.getText();

        CustomerDTO itemDTO = new CustomerDTO(Date, CustomerTelePoneNo, CustomerName, CustomerAddress, CustomerId);
        loadData();
        dtmCustomer = (DefaultTableModel) AllAddCustomerTabel.getModel();
        
        try {
            boolean isUpdate = ctrlCustomer.update(itemDTO);
            if (isUpdate) {
                JOptionPane.showMessageDialog(btnUpdate, "Make Type is updated");
            } else {
                JOptionPane.showMessageDialog(btnUpdate, "Make Type is not updated");
            }
        } catch (Exception ex) {
            Logger.getLogger(allCustomerManagee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AllAddCustomerTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllAddCustomerTabelMouseClicked
        int r = AllAddCustomerTabel.getSelectedRow();
        String CustomerID = AllAddCustomerTabel.getValueAt(r, 0).toString();
        String CustomerName = AllAddCustomerTabel.getValueAt(r, 1).toString();
        String CustomerAddress= AllAddCustomerTabel.getValueAt(r, 2).toString();
        String CustomerTelePoneNo = AllAddCustomerTabel.getValueAt(r, 3).toString();
        String Date = AllAddCustomerTabel.getValueAt(r, 4).toString();

        txtCustomerId.setText(CustomerID);
        txtCustomerName.setText(CustomerName);
        txtCustomerAddress.setText(CustomerAddress);
        txtCustomerTelePoneNo.setText(CustomerTelePoneNo);
        txtDate.setText(Date);
    }//GEN-LAST:event_AllAddCustomerTabelMouseClicked

    private void txtCustomerTelePoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerTelePoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerTelePoneNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JasperReport comJasperReport = (JasperReport)JRLoader.loadObject(AddCustomerFrom.class.getResource("/lk/ijsejasper/report/CustomerReprt_A4.jasper"));
            JasperPrint filledReport = JasperFillManager.fillReport(comJasperReport, new HashMap<>(),new JRTableModelDataSource(AllAddCustomerTabel.getModel()));
            JFileChooser fileChooser = new JFileChooser();

            fileChooser.setAcceptAllFileFilterUsed(false);
            fileChooser.setFileFilter(new FileNameExtensionFilter("HTML Files('.html)", "html"));
            fileChooser.showSaveDialog(this);

            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            filePath+=".html";
            JasperExportManager.exportReportToHtmlFile(filledReport,filePath);

        } catch (JRException ex) {
            Logger.getLogger(AddCustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JasperReport comJasperReport = (JasperReport)JRLoader.loadObject(AddCustomerFrom.class.getResource("/lk/ijsejasper/report/CustomerReprt_A4.jasper"));

            JasperPrint filledReport = JasperFillManager.fillReport(comJasperReport, new HashMap<>(),new JRTableModelDataSource(AllAddCustomerTabel.getModel()));
            mYjasperViewer MyjViewer = new mYjasperViewer(filledReport);
            MyjViewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(AddCustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String customerID = txtSearch.getText();

        try {
            CustomerDTO customerDTO = ctrlCustomer.search(customerID);
            if (customerDTO == null) {
                JOptionPane.showMessageDialog(this, "No Member Found");
            } else {
                txtCustomerId.setText(customerDTO.getId());
                txtCustomerName.setText(customerDTO.getName());
                txtCustomerTelePoneNo.setText(customerDTO.getTelePoneNO());
                txtCustomerAddress.setText(customerDTO.getAddress());
                txtDate.setText(customerDTO.getDate());
               
            }
        } catch (Exception ex) {
            Logger.getLogger(allCustomerManagee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AllAddCustomerTabel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerTelePoneNo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
