/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Thogakade.views;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Thogakade.controller.ControllerFactory;
import lk.ijse.Thogakade.controller.custom.OrderController;
import lk.ijse.Thogakade.controller.custom.OrderDetailController;
import lk.ijse.Thogakade.dto.CustomerDTO;
import lk.ijse.Thogakade.dto.OrderDetailDTO;

/**
 *
 * @author Viraj jayasanka
 */
public class customerPaymentPanel extends javax.swing.JPanel {
    
    private OrderDetailController ctrlOrderD;
    private DefaultTableModel dtmOrder;
    /**
     * Creates new form customerPaymentPanel
     */
    public customerPaymentPanel() {
        initComponents();
        ctrlOrderD = (OrderDetailController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ORDERDETAIL);
        dtmOrder = (DefaultTableModel) OrderDeTabel.getModel();
        loadData();
    }
      private void loadData() {

        dtmOrder.setRowCount(0);

        try {
            ArrayList<OrderDetailDTO> allOrders = ctrlOrderD.getAll();

            if (allOrders == null) {
                return;
            }

            for (OrderDetailDTO orderD : allOrders) {
                Object[] rowData = {
                    orderD.getOrderId(),
                    orderD.getItemCode(),
                    orderD.getItemDescription(),
                    orderD.getUnitPrice(),
                    orderD.getQty(),
                   
                };
                dtmOrder.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(customerPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderDeTabel = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sinhala-Lasitha-1", 2, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/Payment_card_credit_pay_cash.png"))); // NOI18N
        jLabel2.setText("CUSTOMER PAYMENT DETAIL");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, -1));

        OrderDeTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "oderid", "itemCode", " Description", "unitPrice", "itemQTYHand"
            }
        ));
        jScrollPane1.setViewportView(OrderDeTabel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1060, 480));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1060, 10));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/Save button ican.png"))); // NOI18N
        jButton4.setText("SAVE DALY REPORT");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      /*  try {
            JasperReport comJasperReport = (JasperReport)JRLoader.loadObject(AddCustomerFrom.class.getResource("/lk/ijsejasper/report/CustomerReprt_A4.jasper"));
            JasperPrint filledReport = JasperFillManager.fillReport(comJasperReport, new HashMap<>(),new JRTableModelDataSource(AllAddCustomerTabel.getModel()));
            JFileChooser fileChooser = new JFileChooser();

            fileChooser.setAcceptAllFileFilterUsed(false);
            fileChooser.setFileFilter(new FileNameExtensionFilter("HTML Files('.html)", "html"));
            fileChooser.showSaveDialog(this);

            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            filePath+=".html";
            JasperExportManager.exportReportToHtmlFile(filledReport,filePath);

        } catch (JRException ex) {
            Logger.getLogger(AddCustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderDeTabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
