/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Thogakade.views;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Thogakade.common.IDGenerator;
import lk.ijse.Thogakade.controller.ControllerFactory;
import lk.ijse.Thogakade.controller.custom.BatchController;
import lk.ijse.Thogakade.dto.CustomerDTO;
import lk.ijse.Thogakade.dto.batchDTO;

/**
 *
 * @author Viraj jayasanka
 */
public class ItemBatchPanel extends javax.swing.JPanel {
     private BatchController batchController;
     private DefaultTableModel dtmBatch;
    /**
     * Creates new form ItemBatchPanel
     */
    public ItemBatchPanel() {
        initComponents();
         batchController = (BatchController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BATCH);
        dtmBatch = (DefaultTableModel) BatchTabel.getModel();
        setEnable(false);
        loadData();
        BatchID();
        handleEvents();
        
    }

    
    
    private void handleEvents() {

        BatchTabel.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (BatchTabel.getSelectedRowCount() <= 0) {
                    return;
                }

                String customerId = dtmBatch.getValueAt(BatchTabel.getSelectedRow(), 0).toString();
                try {
                    batchDTO batch = batchController.search(customerId);

                    if (batch != null) {
                        txtItemrId.setText(batch.getItemCode());
                        txtBatch.setText(batch.getBatchID());
                        //txtExperDate.setText(batch.getBtchItemExperDate());
                       // txtMfdDate.setText(batch.getBatchItemMFDDate());
                    }
                    setEnable(true, btnSave,txtItemrId);
                    

                } catch (Exception ex) {
                    Logger.getLogger(AddCustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }
    
      private void setEnable(boolean enable, JComponent... cmp) {
        txtItemrId.setEnabled(enable);
        txtBatch.setEnabled(enable);
        jXDatePickerExperDate.setEnabled(enable);
        jXDatePickerMfdDate.setEnabled(enable);
        btnSave.setEnabled(enable);
        btnDelete.setEnabled(enable);
       // removeAlljButton.setEnabled(enable);
        for (JComponent jcmp : cmp) {
            jcmp.setEnabled(!enable);
        }
    }
    
     private void loadData() {

        dtmBatch.setRowCount(0);

        try {
            ArrayList<batchDTO> allBatchs = batchController.getAll();

            if (allBatchs == null) {
                return;
            }

            for (batchDTO batch : allBatchs) {
                Object[] rowData = {
                    batch.getItemCode(),
                    batch.getBatchID(),
                    batch.getBtchItemExperDate(),
                    batch.getBtchItemExperDate(),
                };
                dtmBatch.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(AddCustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private void clearFields() {
        txtItemrId.setText("");
//        txtExperDate.setText("");
        jLabel7.setText("");
//        txtMfdDate.setText("");
        
    }
     
        private void doValidate() {
        String itemCode = txtItemrId.getText();
        String itemBatch = txtBatch.getText();
        String itemname =  jLabel7.getText();
       SeteBtn.setEnabled(true);
                
       BatchTabel.setEnabled(false);

        if (!itemCode.isEmpty()) {
            if (itemBatch.isEmpty()) {
                
                      if (!itemname.isEmpty()) {  
                          
                       
                    BatchTabel.setEnabled(true);
            }
        }
      }
   }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtItemrId = new javax.swing.JTextField();
        SeteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BatchTabel = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnnewCustomer = new javax.swing.JButton();
        jXDatePickerMfdDate = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerExperDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtItemrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 30));

        SeteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SeteBtn.setText("Select Item");
        SeteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SeteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Item Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Batch NO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mfd Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sinhala-Lasitha-1", 3, 36)); // NOI18N
        jLabel5.setText("ITEM BATCH FORM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 430, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Exper Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        txtBatch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 160, 30));

        btnDelete.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/delete customer ican1.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 200, 40));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/Add buton item image.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 200, 40));

        BatchTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "BatchNO", "Mfc Date", "Exper date"
            }
        ));
        jScrollPane1.setViewportView(BatchTabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 1010, 390));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1030, 10));

        btnnewCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/AddItem Ican.png"))); // NOI18N
        btnnewCustomer.setText("NEW ");
        btnnewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnnewCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 230, 40));

        jXDatePickerMfdDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerMfdDateActionPerformed(evt);
            }
        });
        jPanel1.add(jXDatePickerMfdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, 30));
        jPanel1.add(jXDatePickerExperDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 240, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Item Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 200, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void SeteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeteBtnActionPerformed
    AddItemBachpanel a = new AddItemBachpanel();
        a.setVisible(true);
    }//GEN-LAST:event_SeteBtnActionPerformed

    private void btnnewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewCustomerActionPerformed
        clearFields();

        if (dtmBatch.getRowCount() > 0) {
            BatchTabel.getSelectionModel().clearSelection();
        }
      //  setEnable(false, SeteBtn);
        setEnable(true,btnDelete);
        txtBatch.requestFocusInWindow();
      
    }//GEN-LAST:event_btnnewCustomerActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        Date date = jXDatePickerMfdDate.getDate();
        Date dateE = jXDatePickerExperDate.getDate();
        SimpleDateFormat d = new SimpleDateFormat("yyy-MM-dd");
        
        
        batchDTO BatchDTO = new batchDTO(
                txtItemrId.getText(),
                txtBatch.getText(),
                d.format(date),
                d.format(dateE));
        try {
            
            boolean result = false;
            if (txtItemrId.isEnabled()){
                result = batchController.add(BatchDTO);                
            }else{
                result = batchController.update(BatchDTO);
            }
            if (result) {
              
                loadData();
                BatchID();
                clearFields();
                setEnable(false);
                btnnewCustomer.requestFocusInWindow();
                JOptionPane.showMessageDialog(this, "Added success");
            } else {
                JOptionPane.showMessageDialog(this,
                        "Batch Deatil has been failed to add",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                txtItemrId.requestFocusInWindow();
                txtItemrId.selectAll();
            }
        } catch (SQLException ex) {
            String errorMsg;


            switch (ex.getErrorCode()) {
                case 1062:
                    errorMsg = "Duplicate entry has been found. Please enter valid batcId to proceed.";
                    break;
                default:
                    errorMsg = "bach Detail has been failed to add";
                    break;
            }

            JOptionPane.showMessageDialog(this,
                    errorMsg,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            txtItemrId.requestFocusInWindow();
            txtItemrId.selectAll();
        } catch (Exception ex) {
            Logger.getLogger(AddCustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         String batchID = dtmBatch.getValueAt(BatchTabel.getSelectedRow(), 0).toString();
        try {
            boolean deleted = batchController.delete(batchID);
            if (deleted) {
               
                clearFields();
                setEnable(false);
                loadData();
                BatchTabel.clearSelection();
                BatchTabel.requestFocusInWindow();
                JOptionPane.showMessageDialog(this, "Deleted success");
            } else {
                JOptionPane.showMessageDialog(this,
                        "Batch detail deletion has been failed, Please try again.",
                        "Delete Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Batch deletion has been failed, Please try again.",
                    "Delete Error",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AddCustomerFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
                                      
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jXDatePickerMfdDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerMfdDateActionPerformed
        
        
    }//GEN-LAST:event_jXDatePickerMfdDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BatchTabel;
    private javax.swing.JButton SeteBtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnnewCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerExperDate;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerMfdDate;
    private javax.swing.JTextField txtBatch;
    public static javax.swing.JTextField txtItemrId;
    // End of variables declaration//GEN-END:variables

private void BatchID() {
        try {
            String batchID;
            batchID = IDGenerator.getNewID("Batch", "batchID", "C");
           txtBatch.setText(batchID);
        } catch (SQLException ex) {
            Logger.getLogger(ItemBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemBatchPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
   
}
}
