/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Thogakade.views;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import lk.ijse.Thogakade.controller.ControllerFactory;
import lk.ijse.Thogakade.controller.custom.LoginController;
import lk.ijse.Thogakade.dto.LoginDTO;
import lk.ijse.Thogakde.dataEncriptionAndDecription.SecurityImplementation;

/**
 *
 * @author Viraj jayasanka
 */
public class LoingMainPanel extends javax.swing.JFrame {
       private LoginController ctrlLogin;
    /**
     * Creates new form LoingMainPanel
     */
    public LoingMainPanel() {
        initComponents();
        LoginPanel.setBackground(new Color(228,239,186,110));  
        ctrlLogin = (LoginController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.Login);
       // ImageIcon icon = loadIcon();
      //  this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        UserNameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PassWordText = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("PASSWORD");
        LoginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("USER NAME");
        LoginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sinhala-Lasitha-1", 3, 24)); // NOI18N
        jLabel7.setText("JAYSANKA WHOLE SALAE SHOP");
        LoginPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 460, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        LoginPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 190, 30));

        UserNameText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextActionPerformed(evt);
            }
        });
        LoginPanel.add(UserNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 240, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        LoginPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, 30));
        LoginPanel.add(PassWordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 240, 30));

        jPanel1.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 520, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/Login Image.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                
        String username = UserNameText.getText();
        String password = PassWordText.getText();
        if(username.equals("Viraj") && password.equals("1234")){
            ManageMain main = new ManageMain();
            main.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showConfirmDialog(this,"user Or Passoword is Incorrect");
        }
//////        try {
//////            String username = UserNameText.getText();
//////            String password = PassWordText.getText();
//////            String uname = SecurityImplementation.implementationEncript(username);
//////            String pass = SecurityImplementation.implementationEncript(password);
//////            LoginDTO ldto = ctrlLogin.searchLogin(uname, pass);
//////            if (!ldto.getPassword().isEmpty()) {
//////                new ManageMain().setVisible(true);
//////                this.dispose();
//////            }
//////            
//
//        } catch (Exception ex) {
//            Logger.getLogger(LoingMainPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
   
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextActionPerformed
          PassWordText.requestFocus();
    }//GEN-LAST:event_UserNameTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int res = JOptionPane.showConfirmDialog(this, "Do you want to exit");
        if (res == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoingMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoingMainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField PassWordText;
    private javax.swing.JTextField UserNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
