/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Thogakade.views;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Thogakade.controller.ControllerFactory;
import lk.ijse.Thogakade.controller.custom.OrderController;
import lk.ijse.Thogakade.dto.CustomerDTO;
import lk.ijse.Thogakade.dto.OrderDTO;

/**
 *
 * @author Viraj jayasanka
 */
public class oderDeatilPanel extends javax.swing.JPanel {

    private OrderController ctrlOrder;
    private DefaultTableModel dtmOrder;

    /**
     * Creates new form oderDeatilPanel
     */
    public oderDeatilPanel() {

        initComponents();

        ctrlOrder = (OrderController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ORDER);
        dtmOrder = (DefaultTableModel) OrderTabel.getModel();
        loadData();
    }

    private void loadData() {

        dtmOrder.setRowCount(0);

        try {
            ArrayList<OrderDTO> allOrders = ctrlOrder.getAll();

            if (allOrders == null) {
                return;
            }

            for (OrderDTO order : allOrders) {
                Object[] rowData = {
                    order.getId(),
                    order.getDate(),
                    order.getCustomerId(),};
                dtmOrder.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(allCustomerManagee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "CustomerId", "Date"
            }
        ));
        jScrollPane1.setViewportView(OrderTabel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1050, 490));

        jLabel1.setFont(new java.awt.Font("Sinhala-Lasitha-1", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/Order Details.png"))); // NOI18N
        jLabel1.setText("ORDER DEATILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderTabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
