/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.Thogakade.views;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.Thogakade.controller.ControllerFactory;
import lk.ijse.Thogakade.controller.custom.ItemController;
import lk.ijse.Thogakade.dao.custom.impl.ItemDAOImpl;
import lk.ijse.Thogakade.dto.ItemDTO;

/**
 *
 * @author Viraj jayasanka
 */
public class SelectItem extends javax.swing.JFrame {
    private DefaultTableModel dtmItem;
    private ItemController ctrlController;

    /**
     * Creates new form SelectItem
     */
    public SelectItem() {
        initComponents();
        setLocationRelativeTo(null);
        dtmItem = (DefaultTableModel) tblItems.getModel();
        ctrlController = (ItemController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ITEM);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ItemName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameActionPerformed(evt);
            }
        });
        jPanel1.add(ItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 270, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/Thogakade/icons/CLOSE.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Enter Item Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Code", "Description", "Unit Price", "Qty"
            }
        ));
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameActionPerformed
       String name= ItemName.getText();
       try{
           ItemDTO item = ctrlController.searchItemName(name);
           if(item == null){
               JOptionPane.showMessageDialog(this, "item Not found");
           }else{
               System.out.println(item);
               Object [] rowData ={item.getCode(),item.getDescription(),item.getUnitPrice(),item.getQtyOnHand()};
               DefaultTableModel dtm = (DefaultTableModel) tblItems.getModel();
               dtm.setRowCount(0);
               dtm.addRow(rowData);
           }
       } catch (Exception ex) {
            Logger.getLogger(SelectItem.class.getName()).log(Level.SEVERE, null, ex);
        }
         
                                       
    }//GEN-LAST:event_ItemNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
      String itemCode = tblItems.getValueAt(tblItems.getSelectedRow(), 0).toString();
      String description = tblItems.getValueAt(tblItems.getSelectedRow(), 1).toString();
      String unitPrice = tblItems.getValueAt(tblItems.getSelectedRow(),2).toString();
      String qty = tblItems.getValueAt(tblItems.getSelectedRow(),3).toString();
     
     // String qty =  tblItems.getValueAt(tblItems.getSelectedRow(),3).toString();
    //  ManageMain.getOrderFrom().setItemId(itemCode,description,unitPrice,qty);
      
        placeOderFrom.txtItemCode.setText(itemCode);
        placeOderFrom.txtDescription.setText( description);
        placeOderFrom.txtUnitPrice.setText(unitPrice);
        placeOderFrom.txtAvailableQty.setText(qty);
       // ItemBatchPanel.txtItemrId.setText(itemCode);
      //  ItemBatchPanel.txtName.setText(unitPrice);
       // placeOderFrom.txtQty.setText(qty);
       
      
      this.dispose();
    }//GEN-LAST:event_tblItemsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ItemName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables

private void loadData(){
        dtmItem.setRowCount(0);
        try{
            ArrayList<ItemDTO> allItem =ctrlController.getAll();
            if(allItem == null){
             return ;
            }
            for(ItemDTO item :allItem){
                Object[]rowData ={item.getCode(),item.getDescription(),item.getUnitPrice(),item.getQtyOnHand()};
                dtmItem.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(addItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    
 }
}


